### ISSUE TITLE
ISR function doesn't exist

### ISSUE THREAD

**Issue by AskAlice** [sweavo/rotary#1]
Is there a library that is an implied dependency?
I'm using an esp32

https://github.com/sweavo/rotary/blob/master/rotary.cpp#L31

```
c:\Users\alice\Documents\Arduino\libraries\rotary\rotary.cpp:31:4: error: expected constructor, destructor, or type conversion before '(' token
 ISR(TIMER0_COMPA_vect) 
```

**Comment by sweavo** [comment]
Thanks for checking out this code!

My guess is that it's an issue with the ESP target toolchain. I know that the ESP has very different onboard hardware than Arduino.  This library was build for Arduino UNO if I recall right.

To get the alarm "module" working, find a way to call that function every 1ms.  It doesn't need to be precise to be good enough for the rotary library.  I've sketched something that might just work (it's untested) on branch `improvements/esp-test`. 

Pull it and take a look.

**Comment by sweavo** [comment]
I have ESP8266 which has only 2 timers, but it looks like you have 4.  So there is hope that you can find the right macros to set up the handler on a 1ms cycle.  https://techtutorialsx.com/2017/10/07/esp32-arduino-timer-interrupts/ has examples.

**Comment by sweavo** [comment]
Ok, this was fun! I got an ESP32 and hacked it to work.  Branch `improvements/esp-test` works for the rotary on pins 12 and 13, and using timer 0.

**Comment by sweavo** [comment]
Now it's tidied and on master. Thanks for the challenge.
